name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t myheart/patient-service ./patient-service
      - name: Push to Docker Hub
        run: docker push myheart/patient-service
